# $> docker-compose up --build
version: '3.4'
services:
  rails:
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    volumes:
      - ./project:/myapp
      # if you do make changes to your project gems in development, 
      # you will need to remember to delete gem_cache volume 
      # before recreating your application service.
      - gem_cache:/usr/local/bundle/gems
      # if you modify the project’s Node dependencies, 
      # you will need to remove and recreate this volume.
      - node_modules:/app/node_modules
    ports:
      - "80:3000"
    depends_on: 
      - 'db'
    environment:
      RAILS_ENV: development
    # restart: always

  db:
    image: postgres:12.1
    env_file: .env
    # restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin4"
    ports:
      - "8080:8080"
    env_file: .env # configure postgres
    # restart: unless-stopped
    depends_on:
      - 'db'
    volumes:
    - ./servers.json:/pgadmin4/servers.json
    - pgadmin-data:/var/lib/pgadmin
      
volumes:
  gem_cache:
  db_data:
  node_modules:
  pgadmin-data: