development:
  adapter: postgresql

test:
  adapter: postgresql

production:
  adapter: postgresql
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: project_production
